name: django-dpotools CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]
        django-version: ["3.2", "4.2"]
        exclude:
          - python-version: "3.11"
            django-version: "3.2"
    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install gettext
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install packages and set up Django
      run: |
        python -m pip install --upgrade pip wheel
        pip install django~=${{ matrix.django-version }}
        pip install -r requirements-dev-no-django.txt
        python manage.py makemigrations breach rpa
        python manage.py migrate
        django-admin compilemessages
    - name: Run coverage for Python ${{ matrix.python-version }} and Django ${{ matrix.django-version }}
      run: |
        coverage run manage.py test
